require("vim._core.ui2").enable({})
require("opt")
require("packages")
require("builtin")
require("keymaps")
require("autocommands")
require("functions")
require("lsp")

vim.pack.add({ 'https://github.com/zuqini/zpack.nvim' })
require('zpack').setup()
